#!/usr/bin/env bash
# scripts/build.sh — bundle public/index.html into src/worker.js as build/worker.js
#
# The HTML is base64-encoded and prepended as a `const INDEX_HTML_B64 = "..."`
# declaration. Worker uses atob() at cold-start to decode it.

set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p build

if ! command -v base64 >/dev/null; then
  echo "base64 not found — install coreutils" >&2
  exit 1
fi

# -w 0 = no line wrapping (GNU base64). Some platforms use -b 0 or just no flag; try both.
if base64 --help 2>&1 | grep -q -- '-w'; then
  HTML_B64=$(base64 -w 0 public/index.html)
else
  HTML_B64=$(base64 -b 0 public/index.html 2>/dev/null || base64 < public/index.html | tr -d '\n')
fi

{
  echo "// Auto-generated by scripts/build.sh — do not edit directly."
  echo "// Source: src/worker.js + public/index.html"
  echo "const INDEX_HTML_B64 = \"$HTML_B64\";"
  echo ""
  cat src/worker.js
} > build/worker.js

echo "Bundled $(wc -c < build/worker.js) bytes → build/worker.js"
